name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Fix and regenerated Gradle Wrapper
        run: |
          cd android
          gradle wrapper --gradle-version 8.10.2 --distribution-type bin
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          cd ..

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: overtime-yer-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
